blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'blog'

# url 규칙
# /user_id/ => post_list
# /user_id/post/ => 위와 동일
# /user_id/post/slug => post_detail

# /post/create
# /post/slug/update
# /post/slug/delete

# /contents/ => content_list
# /content/99/ => content_detail

# /content/99/update
# /content/99/delete

# /user_id/tags/ => tag_cloud
# /user_id/tag/1 => tag_detail


urlpatterns = [
    path('', IndexView.as_view(), name="index"), # post list
    # path('<int:author_id>/', PostListView.as_view(), name='post_list'),
    path('<str:username>/', PostListView.as_view(), name='post_list'),
    path('<str:username>/<int:pk>', PostDetailView.as_view(), name='post_detail'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('blog/', include('blog.urls')),
    path('', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from tagging.fields import TagField
from django import forms

class Category(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=4)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)
    tag = TagField(blank=True);
    created_date = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return ('blog_post_detail', (),
                {
                    'slug' :self.slug,
                })

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Content(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    type = models.CharField(max_length=50) # file, image, url, youtube, text
    image = models.ImageField(blank=True, upload_to="blog/%Y/%m/%d")
    file = models.FileField(blank=True, upload_to="blog/%Y/%m/%d")
    description = models.TextField(blank=True)
    url = models.URLField(blank=True)
    created_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.type


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, DeleteView
from django.views.generic.list import ListView
from django.utils import timezone
from blog.models import *
from django.contrib.auth.models import User

from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

class IndexView(TemplateView) :
    template_name = 'blog/index.html'

    def get_queryset(self):
        pass

class PostListView(ListView) :
    model = Post
    slug_field = "username"
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self, **kwargs):
        user = get_object_or_404(User, username=self.kwargs['username'])
        return Post.objects.filter(author=user)

class PostDetailView(DeleteView) :
    model = Post
    template_name = 'blog/post_detail.html'


# class PostTOL(TaggedObjectList) :
#     model = Post
#     template_name = 'tagging/tagging_post_list'
#
# class TagTV(TemplateView) :
#     template_name = 'tagging/tagging_tags.html'

blog/templates/blog/_post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index!!</title>
</head>
<body>
<h1>포스트 리스트 뷰</h1>

{% for post in post_list %}
    <h5>작성자 : {{ post.author }}</h5>
    <h5>카테고리 : {{ post.category }}</h5>
    <h5>{{ post.title }}</h5>
    <h5>{{ post.slug }}</h5>
    <h5>{{ post.tag }}</h5>
    <h5>{{ post.created_date }}</h5>
    <hr>
{% endfor %}
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index!!</title>
</head>
<body>
<h1>기본 페이지</h1>
</body>
</html>

blog/templates/blog/post_detail.html
{% load tagging_tags %}
{% tags_for_object object as tags %}
<p>author : {{ post.author }}</p>
<p>category : {{ post.category }}</p>
<p>title : {{ post.title }}</p>
<p>created_date : {{ post.created_date }}</p>
<p>tags : {{ tags }}</p>

{% load disqus_tags %}
{% disqus_show_comments %}

blog/templates/blog/post_list.html
<h2>Posts</h2>
{% for post in posts %}
    {{ post.title }} <br>
    {% for content in post.content_set.all %}
        {{ content.description }}
    {% endfor %}
    <hr>
{% endfor %}